using System;
using System.ComponentModel;
using System.Drawing;
using System.Windows.Forms;
namespace FormsUI
{
	public class NameEntry : Form
	{
		private IContainer components = null;
		private Button button1;
		private Button button2;
		private Button button3;
		private Button button4;
		private Button button5;
		private Button button6;
		private Button button7;
		private Button button8;
		private Button button9;
		private Button button10;
		private Button button11;
		private Button button12;
		private Button button13;
		private Button button14;
		private Button button15;
		private Button button16;
		private Button button17;
		private Button button18;
		private Button button19;
		private Button button20;
		private Button button21;
		private Button button22;
		private Button button23;
		private Button button24;
		private Button button25;
		private Button button26;
		private Button button27;
		private Button button28;
		private Button button29;
		private Button button30;
		private Button button31;
		private Button button32;
		private Button button33;
		private Button button34;
		private Button button35;
		private Button button36;
		private Button button37;
		private Button button38;
		private Button button39;
		private Button button53;
		private Button button54;
		private Button button55;
		private Button button56;
		private Button button57;
		private Button button58;
		private Button button59;
		private Button button60;
		private Button button61;
		private Button button62;
		private Button button63;
		private Button button64;
		private Button button65;
		private Button button40;
		private Button button41;
		private Button button42;
		private Button button43;
		private Button button44;
		private Button button45;
		private Button button46;
		private Button button47;
		private Button button48;
		private Button button49;
		private Button button50;
		private Button button51;
		private Button button52;
		private Button button66;
		private Button button67;
		private Button button68;
		private Button button69;
		private Button btnOK;
		private Button btnDelete;
		private PictureBox pictureBox1;
		private Label lblChar1;
		private Label lblChar2;
		private Label lblChar3;
		private Label lblChar4;
		private Label lblChar5;
		private Label lblChar6;
		private Label lblChar7;
		private string name = "";
		private int pos;
		private Label[] chars;
		protected override void Dispose(bool disposing)
		{
			if (disposing && this.components != null)
			{
				this.components.Dispose();
			}
			base.Dispose(disposing);
		}
		private void InitializeComponent()
		{
			this.button1 = new Button();
			this.button2 = new Button();
			this.button3 = new Button();
			this.button4 = new Button();
			this.button5 = new Button();
			this.button6 = new Button();
			this.button7 = new Button();
			this.button8 = new Button();
			this.button9 = new Button();
			this.button10 = new Button();
			this.button11 = new Button();
			this.button12 = new Button();
			this.button13 = new Button();
			this.button14 = new Button();
			this.button15 = new Button();
			this.button16 = new Button();
			this.button17 = new Button();
			this.button18 = new Button();
			this.button19 = new Button();
			this.button20 = new Button();
			this.button21 = new Button();
			this.button22 = new Button();
			this.button23 = new Button();
			this.button24 = new Button();
			this.button25 = new Button();
			this.button26 = new Button();
			this.button27 = new Button();
			this.button28 = new Button();
			this.button29 = new Button();
			this.button30 = new Button();
			this.button31 = new Button();
			this.button32 = new Button();
			this.button33 = new Button();
			this.button34 = new Button();
			this.button35 = new Button();
			this.button36 = new Button();
			this.button37 = new Button();
			this.button38 = new Button();
			this.button39 = new Button();
			this.button53 = new Button();
			this.button54 = new Button();
			this.button55 = new Button();
			this.button56 = new Button();
			this.button57 = new Button();
			this.button58 = new Button();
			this.button59 = new Button();
			this.button60 = new Button();
			this.button61 = new Button();
			this.button62 = new Button();
			this.button63 = new Button();
			this.button64 = new Button();
			this.button65 = new Button();
			this.button40 = new Button();
			this.button41 = new Button();
			this.button42 = new Button();
			this.button43 = new Button();
			this.button44 = new Button();
			this.button45 = new Button();
			this.button46 = new Button();
			this.button47 = new Button();
			this.button48 = new Button();
			this.button49 = new Button();
			this.button50 = new Button();
			this.button51 = new Button();
			this.button52 = new Button();
			this.button66 = new Button();
			this.button67 = new Button();
			this.button68 = new Button();
			this.button69 = new Button();
			this.btnOK = new Button();
			this.btnDelete = new Button();
			this.pictureBox1 = new PictureBox();
			this.lblChar1 = new Label();
			this.lblChar2 = new Label();
			this.lblChar3 = new Label();
			this.lblChar4 = new Label();
			this.lblChar5 = new Label();
			this.lblChar6 = new Label();
			this.lblChar7 = new Label();
			((ISupportInitialize)this.pictureBox1).BeginInit();
			base.SuspendLayout();
			this.button1.BackColor = Color.FromArgb(0, 64, 64);
			this.button1.FlatAppearance.BorderColor = Color.Green;
			this.button1.FlatAppearance.BorderSize = 2;
			this.button1.FlatStyle = FlatStyle.Flat;
			this.button1.Font = new Font("Arial", 12f, FontStyle.Regular, GraphicsUnit.Point, 0);
			this.button1.ForeColor = Color.White;
			this.button1.Location = new Point(40, 88);
			this.button1.Name = "button1";
			this.button1.Size = new Size(24, 32);
			this.button1.TabIndex = 0;
			this.button1.Text = "A";
			this.button1.UseVisualStyleBackColor = false;
			this.button1.Click += new EventHandler(this.btnLetter_Click);
			this.button2.BackColor = Color.FromArgb(0, 64, 64);
			this.button2.FlatAppearance.BorderColor = Color.Green;
			this.button2.FlatAppearance.BorderSize = 2;
			this.button2.FlatStyle = FlatStyle.Flat;
			this.button2.Font = new Font("Arial", 12f, FontStyle.Regular, GraphicsUnit.Point, 0);
			this.button2.ForeColor = Color.White;
			this.button2.Location = new Point(72, 88);
			this.button2.Name = "button2";
			this.button2.Size = new Size(24, 32);
			this.button2.TabIndex = 1;
			this.button2.Text = "B";
			this.button2.UseVisualStyleBackColor = false;
			this.button2.Click += new EventHandler(this.btnLetter_Click);
			this.button3.BackColor = Color.FromArgb(0, 64, 64);
			this.button3.FlatAppearance.BorderColor = Color.Green;
			this.button3.FlatAppearance.BorderSize = 2;
			this.button3.FlatStyle = FlatStyle.Flat;
			this.button3.Font = new Font("Arial", 12f, FontStyle.Regular, GraphicsUnit.Point, 0);
			this.button3.ForeColor = Color.White;
			this.button3.Location = new Point(104, 88);
			this.button3.Name = "button3";
			this.button3.Size = new Size(24, 32);
			this.button3.TabIndex = 2;
			this.button3.Text = "C";
			this.button3.UseVisualStyleBackColor = false;
			this.button3.Click += new EventHandler(this.btnLetter_Click);
			this.button4.BackColor = Color.FromArgb(0, 64, 64);
			this.button4.FlatAppearance.BorderColor = Color.Green;
			this.button4.FlatAppearance.BorderSize = 2;
			this.button4.FlatStyle = FlatStyle.Flat;
			this.button4.Font = new Font("Arial", 12f, FontStyle.Regular, GraphicsUnit.Point, 0);
			this.button4.ForeColor = Color.White;
			this.button4.Location = new Point(136, 88);
			this.button4.Name = "button4";
			this.button4.Size = new Size(24, 32);
			this.button4.TabIndex = 3;
			this.button4.Text = "D";
			this.button4.UseVisualStyleBackColor = false;
			this.button4.Click += new EventHandler(this.btnLetter_Click);
			this.button5.BackColor = Color.FromArgb(0, 64, 64);
			this.button5.FlatAppearance.BorderColor = Color.Green;
			this.button5.FlatAppearance.BorderSize = 2;
			this.button5.FlatStyle = FlatStyle.Flat;
			this.button5.Font = new Font("Arial", 12f, FontStyle.Regular, GraphicsUnit.Point, 0);
			this.button5.ForeColor = Color.White;
			this.button5.Location = new Point(168, 88);
			this.button5.Name = "button5";
			this.button5.Size = new Size(24, 32);
			this.button5.TabIndex = 4;
			this.button5.Text = "E";
			this.button5.UseVisualStyleBackColor = false;
			this.button5.Click += new EventHandler(this.btnLetter_Click);
			this.button6.BackColor = Color.FromArgb(0, 64, 64);
			this.button6.FlatAppearance.BorderColor = Color.Green;
			this.button6.FlatAppearance.BorderSize = 2;
			this.button6.FlatStyle = FlatStyle.Flat;
			this.button6.Font = new Font("Arial", 12f, FontStyle.Regular, GraphicsUnit.Point, 0);
			this.button6.ForeColor = Color.White;
			this.button6.Location = new Point(200, 88);
			this.button6.Name = "button6";
			this.button6.Size = new Size(24, 32);
			this.button6.TabIndex = 5;
			this.button6.Text = "F";
			this.button6.UseVisualStyleBackColor = false;
			this.button6.Click += new EventHandler(this.btnLetter_Click);
			this.button7.BackColor = Color.FromArgb(0, 64, 64);
			this.button7.FlatAppearance.BorderColor = Color.Green;
			this.button7.FlatAppearance.BorderSize = 2;
			this.button7.FlatStyle = FlatStyle.Flat;
			this.button7.Font = new Font("Arial", 12f, FontStyle.Regular, GraphicsUnit.Point, 0);
			this.button7.ForeColor = Color.White;
			this.button7.Location = new Point(232, 88);
			this.button7.Name = "button7";
			this.button7.Size = new Size(24, 32);
			this.button7.TabIndex = 6;
			this.button7.Text = "G";
			this.button7.UseVisualStyleBackColor = false;
			this.button7.Click += new EventHandler(this.btnLetter_Click);
			this.button8.BackColor = Color.FromArgb(0, 64, 64);
			this.button8.FlatAppearance.BorderColor = Color.Green;
			this.button8.FlatAppearance.BorderSize = 2;
			this.button8.FlatStyle = FlatStyle.Flat;
			this.button8.Font = new Font("Arial", 12f, FontStyle.Regular, GraphicsUnit.Point, 0);
			this.button8.ForeColor = Color.White;
			this.button8.Location = new Point(264, 88);
			this.button8.Name = "button8";
			this.button8.Size = new Size(24, 32);
			this.button8.TabIndex = 7;
			this.button8.Text = "H";
			this.button8.UseVisualStyleBackColor = false;
			this.button8.Click += new EventHandler(this.btnLetter_Click);
			this.button9.BackColor = Color.FromArgb(0, 64, 64);
			this.button9.FlatAppearance.BorderColor = Color.Green;
			this.button9.FlatAppearance.BorderSize = 2;
			this.button9.FlatStyle = FlatStyle.Flat;
			this.button9.Font = new Font("Arial", 12f, FontStyle.Regular, GraphicsUnit.Point, 0);
			this.button9.ForeColor = Color.White;
			this.button9.Location = new Point(296, 88);
			this.button9.Name = "button9";
			this.button9.Size = new Size(24, 32);
			this.button9.TabIndex = 8;
			this.button9.Text = "I";
			this.button9.UseVisualStyleBackColor = false;
			this.button9.Click += new EventHandler(this.btnLetter_Click);
			this.button10.BackColor = Color.FromArgb(0, 64, 64);
			this.button10.FlatAppearance.BorderColor = Color.Green;
			this.button10.FlatAppearance.BorderSize = 2;
			this.button10.FlatStyle = FlatStyle.Flat;
			this.button10.Font = new Font("Arial", 12f, FontStyle.Regular, GraphicsUnit.Point, 0);
			this.button10.ForeColor = Color.White;
			this.button10.Location = new Point(328, 88);
			this.button10.Name = "button10";
			this.button10.Size = new Size(24, 32);
			this.button10.TabIndex = 9;
			this.button10.Text = "J";
			this.button10.UseVisualStyleBackColor = false;
			this.button10.Click += new EventHandler(this.btnLetter_Click);
			this.button11.BackColor = Color.FromArgb(0, 64, 64);
			this.button11.FlatAppearance.BorderColor = Color.Green;
			this.button11.FlatAppearance.BorderSize = 2;
			this.button11.FlatStyle = FlatStyle.Flat;
			this.button11.Font = new Font("Arial", 12f, FontStyle.Regular, GraphicsUnit.Point, 0);
			this.button11.ForeColor = Color.White;
			this.button11.Location = new Point(360, 88);
			this.button11.Name = "button11";
			this.button11.Size = new Size(24, 32);
			this.button11.TabIndex = 10;
			this.button11.Text = " ";
			this.button11.UseVisualStyleBackColor = false;
			this.button11.Click += new EventHandler(this.btnLetter_Click);
			this.button12.BackColor = Color.FromArgb(0, 64, 64);
			this.button12.FlatAppearance.BorderColor = Color.Green;
			this.button12.FlatAppearance.BorderSize = 2;
			this.button12.FlatStyle = FlatStyle.Flat;
			this.button12.Font = new Font("Arial", 12f, FontStyle.Regular, GraphicsUnit.Point, 0);
			this.button12.ForeColor = Color.White;
			this.button12.Location = new Point(72, 128);
			this.button12.Name = "button12";
			this.button12.Size = new Size(24, 32);
			this.button12.TabIndex = 11;
			this.button12.Text = "L";
			this.button12.UseVisualStyleBackColor = false;
			this.button12.Click += new EventHandler(this.btnLetter_Click);
			this.button13.BackColor = Color.FromArgb(0, 64, 64);
			this.button13.FlatAppearance.BorderColor = Color.Green;
			this.button13.FlatAppearance.BorderSize = 2;
			this.button13.FlatStyle = FlatStyle.Flat;
			this.button13.Font = new Font("Arial", 12f, FontStyle.Regular, GraphicsUnit.Point, 0);
			this.button13.ForeColor = Color.White;
			this.button13.Location = new Point(104, 128);
			this.button13.Name = "button13";
			this.button13.Size = new Size(24, 32);
			this.button13.TabIndex = 12;
			this.button13.Text = "M";
			this.button13.UseVisualStyleBackColor = false;
			this.button13.Click += new EventHandler(this.btnLetter_Click);
			this.button14.BackColor = Color.FromArgb(0, 64, 64);
			this.button14.FlatAppearance.BorderColor = Color.Green;
			this.button14.FlatAppearance.BorderSize = 2;
			this.button14.FlatStyle = FlatStyle.Flat;
			this.button14.Font = new Font("Arial", 12f, FontStyle.Regular, GraphicsUnit.Point, 0);
			this.button14.ForeColor = Color.White;
			this.button14.Location = new Point(200, 168);
			this.button14.Name = "button14";
			this.button14.Size = new Size(24, 32);
			this.button14.TabIndex = 25;
			this.button14.Text = "Z";
			this.button14.UseVisualStyleBackColor = false;
			this.button14.Click += new EventHandler(this.btnLetter_Click);
			this.button15.BackColor = Color.FromArgb(0, 64, 64);
			this.button15.FlatAppearance.BorderColor = Color.Green;
			this.button15.FlatAppearance.BorderSize = 2;
			this.button15.FlatStyle = FlatStyle.Flat;
			this.button15.Font = new Font("Arial", 12f, FontStyle.Regular, GraphicsUnit.Point, 0);
			this.button15.ForeColor = Color.White;
			this.button15.Location = new Point(168, 168);
			this.button15.Name = "button15";
			this.button15.Size = new Size(24, 32);
			this.button15.TabIndex = 24;
			this.button15.Text = "Y";
			this.button15.UseVisualStyleBackColor = false;
			this.button15.Click += new EventHandler(this.btnLetter_Click);
			this.button16.BackColor = Color.FromArgb(0, 64, 64);
			this.button16.FlatAppearance.BorderColor = Color.Green;
			this.button16.FlatAppearance.BorderSize = 2;
			this.button16.FlatStyle = FlatStyle.Flat;
			this.button16.Font = new Font("Arial", 12f, FontStyle.Regular, GraphicsUnit.Point, 0);
			this.button16.ForeColor = Color.White;
			this.button16.Location = new Point(136, 168);
			this.button16.Name = "button16";
			this.button16.Size = new Size(24, 32);
			this.button16.TabIndex = 23;
			this.button16.Text = "X";
			this.button16.UseVisualStyleBackColor = false;
			this.button16.Click += new EventHandler(this.btnLetter_Click);
			this.button17.BackColor = Color.FromArgb(0, 64, 64);
			this.button17.FlatAppearance.BorderColor = Color.Green;
			this.button17.FlatAppearance.BorderSize = 2;
			this.button17.FlatStyle = FlatStyle.Flat;
			this.button17.Font = new Font("Arial", 12f, FontStyle.Regular, GraphicsUnit.Point, 0);
			this.button17.ForeColor = Color.White;
			this.button17.Location = new Point(104, 168);
			this.button17.Name = "button17";
			this.button17.Size = new Size(24, 32);
			this.button17.TabIndex = 22;
			this.button17.Text = "W";
			this.button17.UseVisualStyleBackColor = false;
			this.button17.Click += new EventHandler(this.btnLetter_Click);
			this.button18.BackColor = Color.FromArgb(0, 64, 64);
			this.button18.FlatAppearance.BorderColor = Color.Green;
			this.button18.FlatAppearance.BorderSize = 2;
			this.button18.FlatStyle = FlatStyle.Flat;
			this.button18.Font = new Font("Arial", 12f, FontStyle.Regular, GraphicsUnit.Point, 0);
			this.button18.ForeColor = Color.White;
			this.button18.Location = new Point(72, 168);
			this.button18.Name = "button18";
			this.button18.Size = new Size(24, 32);
			this.button18.TabIndex = 21;
			this.button18.Text = "V";
			this.button18.UseVisualStyleBackColor = false;
			this.button18.Click += new EventHandler(this.btnLetter_Click);
			this.button19.BackColor = Color.FromArgb(0, 64, 64);
			this.button19.FlatAppearance.BorderColor = Color.Green;
			this.button19.FlatAppearance.BorderSize = 2;
			this.button19.FlatStyle = FlatStyle.Flat;
			this.button19.Font = new Font("Arial", 12f, FontStyle.Regular, GraphicsUnit.Point, 0);
			this.button19.ForeColor = Color.White;
			this.button19.Location = new Point(40, 168);
			this.button19.Name = "button19";
			this.button19.Size = new Size(24, 32);
			this.button19.TabIndex = 20;
			this.button19.Text = "U";
			this.button19.UseVisualStyleBackColor = false;
			this.button19.Click += new EventHandler(this.btnLetter_Click);
			this.button20.BackColor = Color.FromArgb(0, 64, 64);
			this.button20.FlatAppearance.BorderColor = Color.Green;
			this.button20.FlatAppearance.BorderSize = 2;
			this.button20.FlatStyle = FlatStyle.Flat;
			this.button20.Font = new Font("Arial", 12f, FontStyle.Regular, GraphicsUnit.Point, 0);
			this.button20.ForeColor = Color.White;
			this.button20.Location = new Point(328, 128);
			this.button20.Name = "button20";
			this.button20.Size = new Size(24, 32);
			this.button20.TabIndex = 19;
			this.button20.Text = "T";
			this.button20.UseVisualStyleBackColor = false;
			this.button20.Click += new EventHandler(this.btnLetter_Click);
			this.button21.BackColor = Color.FromArgb(0, 64, 64);
			this.button21.FlatAppearance.BorderColor = Color.Green;
			this.button21.FlatAppearance.BorderSize = 2;
			this.button21.FlatStyle = FlatStyle.Flat;
			this.button21.Font = new Font("Arial", 12f, FontStyle.Regular, GraphicsUnit.Point, 0);
			this.button21.ForeColor = Color.White;
			this.button21.Location = new Point(296, 128);
			this.button21.Name = "button21";
			this.button21.Size = new Size(24, 32);
			this.button21.TabIndex = 18;
			this.button21.Text = "S";
			this.button21.UseVisualStyleBackColor = false;
			this.button21.Click += new EventHandler(this.btnLetter_Click);
			this.button22.BackColor = Color.FromArgb(0, 64, 64);
			this.button22.FlatAppearance.BorderColor = Color.Green;
			this.button22.FlatAppearance.BorderSize = 2;
			this.button22.FlatStyle = FlatStyle.Flat;
			this.button22.Font = new Font("Arial", 12f, FontStyle.Regular, GraphicsUnit.Point, 0);
			this.button22.ForeColor = Color.White;
			this.button22.Location = new Point(264, 128);
			this.button22.Name = "button22";
			this.button22.Size = new Size(24, 32);
			this.button22.TabIndex = 17;
			this.button22.Text = "R";
			this.button22.UseVisualStyleBackColor = false;
			this.button22.Click += new EventHandler(this.btnLetter_Click);
			this.button23.BackColor = Color.FromArgb(0, 64, 64);
			this.button23.FlatAppearance.BorderColor = Color.Green;
			this.button23.FlatAppearance.BorderSize = 2;
			this.button23.FlatStyle = FlatStyle.Flat;
			this.button23.Font = new Font("Arial", 12f, FontStyle.Regular, GraphicsUnit.Point, 0);
			this.button23.ForeColor = Color.White;
			this.button23.Location = new Point(232, 128);
			this.button23.Name = "button23";
			this.button23.Size = new Size(24, 32);
			this.button23.TabIndex = 16;
			this.button23.Text = "Q";
			this.button23.UseVisualStyleBackColor = false;
			this.button23.Click += new EventHandler(this.btnLetter_Click);
			this.button24.BackColor = Color.FromArgb(0, 64, 64);
			this.button24.FlatAppearance.BorderColor = Color.Green;
			this.button24.FlatAppearance.BorderSize = 2;
			this.button24.FlatStyle = FlatStyle.Flat;
			this.button24.Font = new Font("Arial", 12f, FontStyle.Regular, GraphicsUnit.Point, 0);
			this.button24.ForeColor = Color.White;
			this.button24.Location = new Point(200, 128);
			this.button24.Name = "button24";
			this.button24.Size = new Size(24, 32);
			this.button24.TabIndex = 15;
			this.button24.Text = "P";
			this.button24.UseVisualStyleBackColor = false;
			this.button24.Click += new EventHandler(this.btnLetter_Click);
			this.button25.BackColor = Color.FromArgb(0, 64, 64);
			this.button25.FlatAppearance.BorderColor = Color.Green;
			this.button25.FlatAppearance.BorderSize = 2;
			this.button25.FlatStyle = FlatStyle.Flat;
			this.button25.Font = new Font("Arial", 12f, FontStyle.Regular, GraphicsUnit.Point, 0);
			this.button25.ForeColor = Color.White;
			this.button25.Location = new Point(168, 128);
			this.button25.Name = "button25";
			this.button25.Size = new Size(24, 32);
			this.button25.TabIndex = 14;
			this.button25.Text = "O";
			this.button25.UseVisualStyleBackColor = false;
			this.button25.Click += new EventHandler(this.btnLetter_Click);
			this.button26.BackColor = Color.FromArgb(0, 64, 64);
			this.button26.FlatAppearance.BorderColor = Color.Green;
			this.button26.FlatAppearance.BorderSize = 2;
			this.button26.FlatStyle = FlatStyle.Flat;
			this.button26.Font = new Font("Arial", 12f, FontStyle.Regular, GraphicsUnit.Point, 0);
			this.button26.ForeColor = Color.White;
			this.button26.Location = new Point(136, 128);
			this.button26.Name = "button26";
			this.button26.Size = new Size(24, 32);
			this.button26.TabIndex = 13;
			this.button26.Text = "N";
			this.button26.UseVisualStyleBackColor = false;
			this.button26.Click += new EventHandler(this.btnLetter_Click);
			this.button27.BackColor = Color.FromArgb(0, 64, 64);
			this.button27.FlatAppearance.BorderColor = Color.Green;
			this.button27.FlatAppearance.BorderSize = 2;
			this.button27.FlatStyle = FlatStyle.Flat;
			this.button27.Font = new Font("Arial", 12f, FontStyle.Regular, GraphicsUnit.Point, 0);
			this.button27.ForeColor = Color.White;
			this.button27.Location = new Point(40, 128);
			this.button27.Name = "button27";
			this.button27.Size = new Size(24, 32);
			this.button27.TabIndex = 38;
			this.button27.Text = "K";
			this.button27.UseVisualStyleBackColor = false;
			this.button27.Click += new EventHandler(this.btnLetter_Click);
			this.button28.BackColor = Color.FromArgb(0, 64, 64);
			this.button28.FlatAppearance.BorderColor = Color.Green;
			this.button28.FlatAppearance.BorderSize = 2;
			this.button28.FlatStyle = FlatStyle.Flat;
			this.button28.Font = new Font("Arial", 12f, FontStyle.Regular, GraphicsUnit.Point, 0);
			this.button28.ForeColor = Color.White;
			this.button28.Location = new Point(424, 128);
			this.button28.Name = "button28";
			this.button28.Size = new Size(24, 32);
			this.button28.TabIndex = 37;
			this.button28.Text = "-";
			this.button28.UseVisualStyleBackColor = false;
			this.button28.Click += new EventHandler(this.btnLetter_Click);
			this.button29.BackColor = Color.FromArgb(0, 64, 64);
			this.button29.FlatAppearance.BorderColor = Color.Green;
			this.button29.FlatAppearance.BorderSize = 2;
			this.button29.FlatStyle = FlatStyle.Flat;
			this.button29.Font = new Font("Arial", 12f, FontStyle.Regular, GraphicsUnit.Point, 0);
			this.button29.ForeColor = Color.White;
			this.button29.Location = new Point(392, 128);
			this.button29.Name = "button29";
			this.button29.Size = new Size(24, 32);
			this.button29.TabIndex = 36;
			this.button29.Text = "'";
			this.button29.UseVisualStyleBackColor = false;
			this.button29.Click += new EventHandler(this.btnLetter_Click);
			this.button30.BackColor = Color.FromArgb(0, 64, 64);
			this.button30.FlatAppearance.BorderColor = Color.Green;
			this.button30.FlatAppearance.BorderSize = 2;
			this.button30.FlatStyle = FlatStyle.Flat;
			this.button30.Font = new Font("Arial", 12f, FontStyle.Regular, GraphicsUnit.Point, 0);
			this.button30.ForeColor = Color.White;
			this.button30.Location = new Point(424, 168);
			this.button30.Name = "button30";
			this.button30.Size = new Size(24, 32);
			this.button30.TabIndex = 35;
			this.button30.Text = "♀";
			this.button30.UseVisualStyleBackColor = false;
			this.button30.Click += new EventHandler(this.btnLetter_Click);
			this.button31.BackColor = Color.FromArgb(0, 64, 64);
			this.button31.FlatAppearance.BorderColor = Color.Green;
			this.button31.FlatAppearance.BorderSize = 2;
			this.button31.FlatStyle = FlatStyle.Flat;
			this.button31.Font = new Font("Arial", 12f, FontStyle.Regular, GraphicsUnit.Point, 0);
			this.button31.ForeColor = Color.White;
			this.button31.Location = new Point(392, 168);
			this.button31.Name = "button31";
			this.button31.Size = new Size(24, 32);
			this.button31.TabIndex = 34;
			this.button31.Text = "♂";
			this.button31.UseVisualStyleBackColor = false;
			this.button31.Click += new EventHandler(this.btnLetter_Click);
			this.button32.BackColor = Color.FromArgb(0, 64, 64);
			this.button32.FlatAppearance.BorderColor = Color.Green;
			this.button32.FlatAppearance.BorderSize = 2;
			this.button32.FlatStyle = FlatStyle.Flat;
			this.button32.Font = new Font("Arial", 12f, FontStyle.Regular, GraphicsUnit.Point, 0);
			this.button32.ForeColor = Color.White;
			this.button32.Location = new Point(360, 168);
			this.button32.Name = "button32";
			this.button32.Size = new Size(24, 32);
			this.button32.TabIndex = 33;
			this.button32.Text = " ";
			this.button32.UseVisualStyleBackColor = false;
			this.button32.Click += new EventHandler(this.btnLetter_Click);
			this.button33.BackColor = Color.FromArgb(0, 64, 64);
			this.button33.FlatAppearance.BorderColor = Color.Green;
			this.button33.FlatAppearance.BorderSize = 2;
			this.button33.FlatStyle = FlatStyle.Flat;
			this.button33.Font = new Font("Arial", 12f, FontStyle.Regular, GraphicsUnit.Point, 0);
			this.button33.ForeColor = Color.White;
			this.button33.Location = new Point(328, 168);
			this.button33.Name = "button33";
			this.button33.Size = new Size(24, 32);
			this.button33.TabIndex = 32;
			this.button33.Text = " ";
			this.button33.UseVisualStyleBackColor = false;
			this.button33.Click += new EventHandler(this.btnLetter_Click);
			this.button34.BackColor = Color.FromArgb(0, 64, 64);
			this.button34.FlatAppearance.BorderColor = Color.Green;
			this.button34.FlatAppearance.BorderSize = 2;
			this.button34.FlatStyle = FlatStyle.Flat;
			this.button34.Font = new Font("Arial", 12f, FontStyle.Regular, GraphicsUnit.Point, 0);
			this.button34.ForeColor = Color.White;
			this.button34.Location = new Point(296, 168);
			this.button34.Name = "button34";
			this.button34.Size = new Size(24, 32);
			this.button34.TabIndex = 31;
			this.button34.Text = " ";
			this.button34.UseVisualStyleBackColor = false;
			this.button34.Click += new EventHandler(this.btnLetter_Click);
			this.button35.BackColor = Color.FromArgb(0, 64, 64);
			this.button35.FlatAppearance.BorderColor = Color.Green;
			this.button35.FlatAppearance.BorderSize = 2;
			this.button35.FlatStyle = FlatStyle.Flat;
			this.button35.Font = new Font("Arial", 12f, FontStyle.Regular, GraphicsUnit.Point, 0);
			this.button35.ForeColor = Color.White;
			this.button35.Location = new Point(264, 168);
			this.button35.Name = "button35";
			this.button35.Size = new Size(24, 32);
			this.button35.TabIndex = 30;
			this.button35.Text = " ";
			this.button35.UseVisualStyleBackColor = false;
			this.button35.Click += new EventHandler(this.btnLetter_Click);
			this.button36.BackColor = Color.FromArgb(0, 64, 64);
			this.button36.FlatAppearance.BorderColor = Color.Green;
			this.button36.FlatAppearance.BorderSize = 2;
			this.button36.FlatStyle = FlatStyle.Flat;
			this.button36.Font = new Font("Arial", 12f, FontStyle.Regular, GraphicsUnit.Point, 0);
			this.button36.ForeColor = Color.White;
			this.button36.Location = new Point(232, 168);
			this.button36.Name = "button36";
			this.button36.Size = new Size(24, 32);
			this.button36.TabIndex = 29;
			this.button36.Text = " ";
			this.button36.UseVisualStyleBackColor = false;
			this.button36.Click += new EventHandler(this.btnLetter_Click);
			this.button37.BackColor = Color.FromArgb(0, 64, 64);
			this.button37.FlatAppearance.BorderColor = Color.Green;
			this.button37.FlatAppearance.BorderSize = 2;
			this.button37.FlatStyle = FlatStyle.Flat;
			this.button37.Font = new Font("Arial", 12f, FontStyle.Regular, GraphicsUnit.Point, 0);
			this.button37.ForeColor = Color.White;
			this.button37.Location = new Point(424, 248);
			this.button37.Name = "button37";
			this.button37.Size = new Size(24, 32);
			this.button37.TabIndex = 28;
			this.button37.Text = " ";
			this.button37.UseVisualStyleBackColor = false;
			this.button37.Click += new EventHandler(this.btnLetter_Click);
			this.button38.BackColor = Color.FromArgb(0, 64, 64);
			this.button38.FlatAppearance.BorderColor = Color.Green;
			this.button38.FlatAppearance.BorderSize = 2;
			this.button38.FlatStyle = FlatStyle.Flat;
			this.button38.Font = new Font("Arial", 12f, FontStyle.Regular, GraphicsUnit.Point, 0);
			this.button38.ForeColor = Color.White;
			this.button38.Location = new Point(392, 248);
			this.button38.Name = "button38";
			this.button38.Size = new Size(24, 32);
			this.button38.TabIndex = 27;
			this.button38.Text = " ";
			this.button38.UseVisualStyleBackColor = false;
			this.button38.Click += new EventHandler(this.btnLetter_Click);
			this.button39.BackColor = Color.FromArgb(0, 64, 64);
			this.button39.FlatAppearance.BorderColor = Color.Green;
			this.button39.FlatAppearance.BorderSize = 2;
			this.button39.FlatStyle = FlatStyle.Flat;
			this.button39.Font = new Font("Arial", 12f, FontStyle.Regular, GraphicsUnit.Point, 0);
			this.button39.ForeColor = Color.White;
			this.button39.Location = new Point(360, 248);
			this.button39.Name = "button39";
			this.button39.Size = new Size(24, 32);
			this.button39.TabIndex = 26;
			this.button39.Text = " ";
			this.button39.UseVisualStyleBackColor = false;
			this.button39.Click += new EventHandler(this.btnLetter_Click);
			this.button53.BackColor = Color.FromArgb(0, 64, 64);
			this.button53.FlatAppearance.BorderColor = Color.Green;
			this.button53.FlatAppearance.BorderSize = 2;
			this.button53.FlatStyle = FlatStyle.Flat;
			this.button53.Font = new Font("Arial", 12f, FontStyle.Regular, GraphicsUnit.Point, 0);
			this.button53.ForeColor = Color.White;
			this.button53.Location = new Point(360, 128);
			this.button53.Name = "button53";
			this.button53.Size = new Size(24, 32);
			this.button53.TabIndex = 64;
			this.button53.Text = " ";
			this.button53.UseVisualStyleBackColor = false;
			this.button53.Click += new EventHandler(this.btnLetter_Click);
			this.button54.BackColor = Color.FromArgb(0, 64, 64);
			this.button54.FlatAppearance.BorderColor = Color.Green;
			this.button54.FlatAppearance.BorderSize = 2;
			this.button54.FlatStyle = FlatStyle.Flat;
			this.button54.Font = new Font("Arial", 12f, FontStyle.Regular, GraphicsUnit.Point, 0);
			this.button54.ForeColor = Color.White;
			this.button54.Location = new Point(392, 88);
			this.button54.Name = "button54";
			this.button54.Size = new Size(24, 32);
			this.button54.TabIndex = 63;
			this.button54.Text = ",";
			this.button54.UseVisualStyleBackColor = false;
			this.button54.Click += new EventHandler(this.btnLetter_Click);
			this.button55.BackColor = Color.FromArgb(0, 64, 64);
			this.button55.FlatAppearance.BorderColor = Color.Green;
			this.button55.FlatAppearance.BorderSize = 2;
			this.button55.FlatStyle = FlatStyle.Flat;
			this.button55.Font = new Font("Arial", 12f, FontStyle.Regular, GraphicsUnit.Point, 0);
			this.button55.ForeColor = Color.White;
			this.button55.Location = new Point(424, 88);
			this.button55.Name = "button55";
			this.button55.Size = new Size(24, 32);
			this.button55.TabIndex = 62;
			this.button55.Text = ".";
			this.button55.UseVisualStyleBackColor = false;
			this.button55.Click += new EventHandler(this.btnLetter_Click);
			this.button56.BackColor = Color.FromArgb(0, 64, 64);
			this.button56.FlatAppearance.BorderColor = Color.Green;
			this.button56.FlatAppearance.BorderSize = 2;
			this.button56.FlatStyle = FlatStyle.Flat;
			this.button56.Font = new Font("Arial", 12f, FontStyle.Regular, GraphicsUnit.Point, 0);
			this.button56.ForeColor = Color.White;
			this.button56.Location = new Point(328, 248);
			this.button56.Name = "button56";
			this.button56.Size = new Size(24, 32);
			this.button56.TabIndex = 61;
			this.button56.Text = "9";
			this.button56.UseVisualStyleBackColor = false;
			this.button56.Click += new EventHandler(this.btnLetter_Click);
			this.button57.BackColor = Color.FromArgb(0, 64, 64);
			this.button57.FlatAppearance.BorderColor = Color.Green;
			this.button57.FlatAppearance.BorderSize = 2;
			this.button57.FlatStyle = FlatStyle.Flat;
			this.button57.Font = new Font("Arial", 12f, FontStyle.Regular, GraphicsUnit.Point, 0);
			this.button57.ForeColor = Color.White;
			this.button57.Location = new Point(296, 248);
			this.button57.Name = "button57";
			this.button57.Size = new Size(24, 32);
			this.button57.TabIndex = 60;
			this.button57.Text = "8";
			this.button57.UseVisualStyleBackColor = false;
			this.button57.Click += new EventHandler(this.btnLetter_Click);
			this.button58.BackColor = Color.FromArgb(0, 64, 64);
			this.button58.FlatAppearance.BorderColor = Color.Green;
			this.button58.FlatAppearance.BorderSize = 2;
			this.button58.FlatStyle = FlatStyle.Flat;
			this.button58.Font = new Font("Arial", 12f, FontStyle.Regular, GraphicsUnit.Point, 0);
			this.button58.ForeColor = Color.White;
			this.button58.Location = new Point(264, 248);
			this.button58.Name = "button58";
			this.button58.Size = new Size(24, 32);
			this.button58.TabIndex = 59;
			this.button58.Text = "7";
			this.button58.UseVisualStyleBackColor = false;
			this.button58.Click += new EventHandler(this.btnLetter_Click);
			this.button59.BackColor = Color.FromArgb(0, 64, 64);
			this.button59.FlatAppearance.BorderColor = Color.Green;
			this.button59.FlatAppearance.BorderSize = 2;
			this.button59.FlatStyle = FlatStyle.Flat;
			this.button59.Font = new Font("Arial", 12f, FontStyle.Regular, GraphicsUnit.Point, 0);
			this.button59.ForeColor = Color.White;
			this.button59.Location = new Point(232, 248);
			this.button59.Name = "button59";
			this.button59.Size = new Size(24, 32);
			this.button59.TabIndex = 58;
			this.button59.Text = "6";
			this.button59.UseVisualStyleBackColor = false;
			this.button59.Click += new EventHandler(this.btnLetter_Click);
			this.button60.BackColor = Color.FromArgb(0, 64, 64);
			this.button60.FlatAppearance.BorderColor = Color.Green;
			this.button60.FlatAppearance.BorderSize = 2;
			this.button60.FlatStyle = FlatStyle.Flat;
			this.button60.Font = new Font("Arial", 12f, FontStyle.Regular, GraphicsUnit.Point, 0);
			this.button60.ForeColor = Color.White;
			this.button60.Location = new Point(200, 248);
			this.button60.Name = "button60";
			this.button60.Size = new Size(24, 32);
			this.button60.TabIndex = 57;
			this.button60.Text = "5";
			this.button60.UseVisualStyleBackColor = false;
			this.button60.Click += new EventHandler(this.btnLetter_Click);
			this.button61.BackColor = Color.FromArgb(0, 64, 64);
			this.button61.FlatAppearance.BorderColor = Color.Green;
			this.button61.FlatAppearance.BorderSize = 2;
			this.button61.FlatStyle = FlatStyle.Flat;
			this.button61.Font = new Font("Arial", 12f, FontStyle.Regular, GraphicsUnit.Point, 0);
			this.button61.ForeColor = Color.White;
			this.button61.Location = new Point(168, 248);
			this.button61.Name = "button61";
			this.button61.Size = new Size(24, 32);
			this.button61.TabIndex = 56;
			this.button61.Text = "4";
			this.button61.UseVisualStyleBackColor = false;
			this.button61.Click += new EventHandler(this.btnLetter_Click);
			this.button62.BackColor = Color.FromArgb(0, 64, 64);
			this.button62.FlatAppearance.BorderColor = Color.Green;
			this.button62.FlatAppearance.BorderSize = 2;
			this.button62.FlatStyle = FlatStyle.Flat;
			this.button62.Font = new Font("Arial", 12f, FontStyle.Regular, GraphicsUnit.Point, 0);
			this.button62.ForeColor = Color.White;
			this.button62.Location = new Point(136, 248);
			this.button62.Name = "button62";
			this.button62.Size = new Size(24, 32);
			this.button62.TabIndex = 55;
			this.button62.Text = "3";
			this.button62.UseVisualStyleBackColor = false;
			this.button62.Click += new EventHandler(this.btnLetter_Click);
			this.button63.BackColor = Color.FromArgb(0, 64, 64);
			this.button63.FlatAppearance.BorderColor = Color.Green;
			this.button63.FlatAppearance.BorderSize = 2;
			this.button63.FlatStyle = FlatStyle.Flat;
			this.button63.Font = new Font("Arial", 12f, FontStyle.Regular, GraphicsUnit.Point, 0);
			this.button63.ForeColor = Color.White;
			this.button63.Location = new Point(104, 248);
			this.button63.Name = "button63";
			this.button63.Size = new Size(24, 32);
			this.button63.TabIndex = 54;
			this.button63.Text = "2";
			this.button63.UseVisualStyleBackColor = false;
			this.button63.Click += new EventHandler(this.btnLetter_Click);
			this.button64.BackColor = Color.FromArgb(0, 64, 64);
			this.button64.FlatAppearance.BorderColor = Color.Green;
			this.button64.FlatAppearance.BorderSize = 2;
			this.button64.FlatStyle = FlatStyle.Flat;
			this.button64.Font = new Font("Arial", 12f, FontStyle.Regular, GraphicsUnit.Point, 0);
			this.button64.ForeColor = Color.White;
			this.button64.Location = new Point(72, 248);
			this.button64.Name = "button64";
			this.button64.Size = new Size(24, 32);
			this.button64.TabIndex = 53;
			this.button64.Text = "1";
			this.button64.UseVisualStyleBackColor = false;
			this.button64.Click += new EventHandler(this.btnLetter_Click);
			this.button65.BackColor = Color.FromArgb(0, 64, 64);
			this.button65.FlatAppearance.BorderColor = Color.Green;
			this.button65.FlatAppearance.BorderSize = 2;
			this.button65.FlatStyle = FlatStyle.Flat;
			this.button65.Font = new Font("Arial", 12f, FontStyle.Regular, GraphicsUnit.Point, 0);
			this.button65.ForeColor = Color.White;
			this.button65.Location = new Point(40, 248);
			this.button65.Name = "button65";
			this.button65.Size = new Size(24, 32);
			this.button65.TabIndex = 52;
			this.button65.Text = "0";
			this.button65.UseVisualStyleBackColor = false;
			this.button65.Click += new EventHandler(this.btnLetter_Click);
			this.button40.BackColor = Color.FromArgb(0, 64, 64);
			this.button40.FlatAppearance.BorderColor = Color.Green;
			this.button40.FlatAppearance.BorderSize = 2;
			this.button40.FlatStyle = FlatStyle.Flat;
			this.button40.Font = new Font("Arial", 12f, FontStyle.Regular, GraphicsUnit.Point, 0);
			this.button40.ForeColor = Color.White;
			this.button40.Location = new Point(40, 208);
			this.button40.Name = "button40";
			this.button40.Size = new Size(24, 32);
			this.button40.TabIndex = 65;
			this.button40.Text = " ";
			this.button40.UseVisualStyleBackColor = false;
			this.button40.Click += new EventHandler(this.btnLetter_Click);
			this.button41.BackColor = Color.FromArgb(0, 64, 64);
			this.button41.FlatAppearance.BorderColor = Color.Green;
			this.button41.FlatAppearance.BorderSize = 2;
			this.button41.FlatStyle = FlatStyle.Flat;
			this.button41.Font = new Font("Arial", 12f, FontStyle.Regular, GraphicsUnit.Point, 0);
			this.button41.ForeColor = Color.White;
			this.button41.Location = new Point(72, 208);
			this.button41.Name = "button41";
			this.button41.Size = new Size(24, 32);
			this.button41.TabIndex = 66;
			this.button41.Text = " ";
			this.button41.UseVisualStyleBackColor = false;
			this.button41.Click += new EventHandler(this.btnLetter_Click);
			this.button42.BackColor = Color.FromArgb(0, 64, 64);
			this.button42.FlatAppearance.BorderColor = Color.Green;
			this.button42.FlatAppearance.BorderSize = 2;
			this.button42.FlatStyle = FlatStyle.Flat;
			this.button42.Font = new Font("Arial", 12f, FontStyle.Regular, GraphicsUnit.Point, 0);
			this.button42.ForeColor = Color.White;
			this.button42.Location = new Point(168, 208);
			this.button42.Name = "button42";
			this.button42.Size = new Size(24, 32);
			this.button42.TabIndex = 69;
			this.button42.Text = " ";
			this.button42.UseVisualStyleBackColor = false;
			this.button42.Click += new EventHandler(this.btnLetter_Click);
			this.button43.BackColor = Color.FromArgb(0, 64, 64);
			this.button43.FlatAppearance.BorderColor = Color.Green;
			this.button43.FlatAppearance.BorderSize = 2;
			this.button43.FlatStyle = FlatStyle.Flat;
			this.button43.Font = new Font("Arial", 12f, FontStyle.Regular, GraphicsUnit.Point, 0);
			this.button43.ForeColor = Color.White;
			this.button43.Location = new Point(136, 208);
			this.button43.Name = "button43";
			this.button43.Size = new Size(24, 32);
			this.button43.TabIndex = 68;
			this.button43.Text = " ";
			this.button43.UseVisualStyleBackColor = false;
			this.button43.Click += new EventHandler(this.btnLetter_Click);
			this.button44.BackColor = Color.FromArgb(0, 64, 64);
			this.button44.FlatAppearance.BorderColor = Color.Green;
			this.button44.FlatAppearance.BorderSize = 2;
			this.button44.FlatStyle = FlatStyle.Flat;
			this.button44.Font = new Font("Arial", 12f, FontStyle.Regular, GraphicsUnit.Point, 0);
			this.button44.ForeColor = Color.White;
			this.button44.Location = new Point(104, 208);
			this.button44.Name = "button44";
			this.button44.Size = new Size(24, 32);
			this.button44.TabIndex = 67;
			this.button44.Text = " ";
			this.button44.UseVisualStyleBackColor = false;
			this.button44.Click += new EventHandler(this.btnLetter_Click);
			this.button45.BackColor = Color.FromArgb(0, 64, 64);
			this.button45.FlatAppearance.BorderColor = Color.Green;
			this.button45.FlatAppearance.BorderSize = 2;
			this.button45.FlatStyle = FlatStyle.Flat;
			this.button45.Font = new Font("Arial", 12f, FontStyle.Regular, GraphicsUnit.Point, 0);
			this.button45.ForeColor = Color.White;
			this.button45.Location = new Point(328, 208);
			this.button45.Name = "button45";
			this.button45.Size = new Size(24, 32);
			this.button45.TabIndex = 74;
			this.button45.Text = " ";
			this.button45.UseVisualStyleBackColor = false;
			this.button45.Click += new EventHandler(this.btnLetter_Click);
			this.button46.BackColor = Color.FromArgb(0, 64, 64);
			this.button46.FlatAppearance.BorderColor = Color.Green;
			this.button46.FlatAppearance.BorderSize = 2;
			this.button46.FlatStyle = FlatStyle.Flat;
			this.button46.Font = new Font("Arial", 12f, FontStyle.Regular, GraphicsUnit.Point, 0);
			this.button46.ForeColor = Color.White;
			this.button46.Location = new Point(296, 208);
			this.button46.Name = "button46";
			this.button46.Size = new Size(24, 32);
			this.button46.TabIndex = 73;
			this.button46.Text = " ";
			this.button46.UseVisualStyleBackColor = false;
			this.button46.Click += new EventHandler(this.btnLetter_Click);
			this.button47.BackColor = Color.FromArgb(0, 64, 64);
			this.button47.FlatAppearance.BorderColor = Color.Green;
			this.button47.FlatAppearance.BorderSize = 2;
			this.button47.FlatStyle = FlatStyle.Flat;
			this.button47.Font = new Font("Arial", 12f, FontStyle.Regular, GraphicsUnit.Point, 0);
			this.button47.ForeColor = Color.White;
			this.button47.Location = new Point(264, 208);
			this.button47.Name = "button47";
			this.button47.Size = new Size(24, 32);
			this.button47.TabIndex = 72;
			this.button47.Text = " ";
			this.button47.UseVisualStyleBackColor = false;
			this.button47.Click += new EventHandler(this.btnLetter_Click);
			this.button48.BackColor = Color.FromArgb(0, 64, 64);
			this.button48.FlatAppearance.BorderColor = Color.Green;
			this.button48.FlatAppearance.BorderSize = 2;
			this.button48.FlatStyle = FlatStyle.Flat;
			this.button48.Font = new Font("Arial", 12f, FontStyle.Regular, GraphicsUnit.Point, 0);
			this.button48.ForeColor = Color.White;
			this.button48.Location = new Point(232, 208);
			this.button48.Name = "button48";
			this.button48.Size = new Size(24, 32);
			this.button48.TabIndex = 71;
			this.button48.Text = " ";
			this.button48.UseVisualStyleBackColor = false;
			this.button48.Click += new EventHandler(this.btnLetter_Click);
			this.button49.BackColor = Color.FromArgb(0, 64, 64);
			this.button49.FlatAppearance.BorderColor = Color.Green;
			this.button49.FlatAppearance.BorderSize = 2;
			this.button49.FlatStyle = FlatStyle.Flat;
			this.button49.Font = new Font("Arial", 12f, FontStyle.Regular, GraphicsUnit.Point, 0);
			this.button49.ForeColor = Color.White;
			this.button49.Location = new Point(200, 208);
			this.button49.Name = "button49";
			this.button49.Size = new Size(24, 32);
			this.button49.TabIndex = 70;
			this.button49.Text = " ";
			this.button49.UseVisualStyleBackColor = false;
			this.button49.Click += new EventHandler(this.btnLetter_Click);
			this.button50.BackColor = Color.FromArgb(0, 64, 64);
			this.button50.FlatAppearance.BorderColor = Color.Green;
			this.button50.FlatAppearance.BorderSize = 2;
			this.button50.FlatStyle = FlatStyle.Flat;
			this.button50.Font = new Font("Arial", 12f, FontStyle.Regular, GraphicsUnit.Point, 0);
			this.button50.ForeColor = Color.White;
			this.button50.Location = new Point(424, 208);
			this.button50.Name = "button50";
			this.button50.Size = new Size(24, 32);
			this.button50.TabIndex = 77;
			this.button50.Text = " ";
			this.button50.UseVisualStyleBackColor = false;
			this.button50.Click += new EventHandler(this.btnLetter_Click);
			this.button51.BackColor = Color.FromArgb(0, 64, 64);
			this.button51.FlatAppearance.BorderColor = Color.Green;
			this.button51.FlatAppearance.BorderSize = 2;
			this.button51.FlatStyle = FlatStyle.Flat;
			this.button51.Font = new Font("Arial", 12f, FontStyle.Regular, GraphicsUnit.Point, 0);
			this.button51.ForeColor = Color.White;
			this.button51.Location = new Point(392, 208);
			this.button51.Name = "button51";
			this.button51.Size = new Size(24, 32);
			this.button51.TabIndex = 76;
			this.button51.Text = " ";
			this.button51.UseVisualStyleBackColor = false;
			this.button51.Click += new EventHandler(this.btnLetter_Click);
			this.button52.BackColor = Color.FromArgb(0, 64, 64);
			this.button52.FlatAppearance.BorderColor = Color.Green;
			this.button52.FlatAppearance.BorderSize = 2;
			this.button52.FlatStyle = FlatStyle.Flat;
			this.button52.Font = new Font("Arial", 12f, FontStyle.Regular, GraphicsUnit.Point, 0);
			this.button52.ForeColor = Color.White;
			this.button52.Location = new Point(360, 208);
			this.button52.Name = "button52";
			this.button52.Size = new Size(24, 32);
			this.button52.TabIndex = 75;
			this.button52.Text = " ";
			this.button52.UseVisualStyleBackColor = false;
			this.button52.Click += new EventHandler(this.btnLetter_Click);
			this.button66.BackColor = Color.FromArgb(0, 64, 64);
			this.button66.FlatAppearance.BorderColor = Color.Green;
			this.button66.FlatAppearance.BorderSize = 2;
			this.button66.FlatStyle = FlatStyle.Flat;
			this.button66.Font = new Font("Arial", 12f, FontStyle.Regular, GraphicsUnit.Point, 0);
			this.button66.ForeColor = Color.White;
			this.button66.Location = new Point(24, 288);
			this.button66.Name = "button66";
			this.button66.Size = new Size(80, 32);
			this.button66.TabIndex = 78;
			this.button66.Text = "UPPER";
			this.button66.UseVisualStyleBackColor = false;
			this.button67.BackColor = Color.FromArgb(0, 64, 64);
			this.button67.FlatAppearance.BorderColor = Color.Green;
			this.button67.FlatAppearance.BorderSize = 2;
			this.button67.FlatStyle = FlatStyle.Flat;
			this.button67.Font = new Font("Arial", 12f, FontStyle.Regular, GraphicsUnit.Point, 0);
			this.button67.ForeColor = Color.White;
			this.button67.Location = new Point(104, 288);
			this.button67.Name = "button67";
			this.button67.Size = new Size(64, 32);
			this.button67.TabIndex = 79;
			this.button67.Text = "lower";
			this.button67.UseVisualStyleBackColor = false;
			this.button68.BackColor = Color.FromArgb(0, 64, 64);
			this.button68.FlatAppearance.BorderColor = Color.Green;
			this.button68.FlatAppearance.BorderSize = 2;
			this.button68.FlatStyle = FlatStyle.Flat;
			this.button68.Font = new Font("Arial", 12f, FontStyle.Regular, GraphicsUnit.Point, 0);
			this.button68.ForeColor = Color.White;
			this.button68.Location = new Point(240, 288);
			this.button68.Name = "button68";
			this.button68.Size = new Size(72, 32);
			this.button68.TabIndex = 81;
			this.button68.Text = "qwerty";
			this.button68.UseVisualStyleBackColor = false;
			this.button69.BackColor = Color.FromArgb(0, 64, 64);
			this.button69.FlatAppearance.BorderColor = Color.Green;
			this.button69.FlatAppearance.BorderSize = 2;
			this.button69.FlatStyle = FlatStyle.Flat;
			this.button69.Font = new Font("Arial", 12f, FontStyle.Regular, GraphicsUnit.Point, 0);
			this.button69.ForeColor = Color.White;
			this.button69.Location = new Point(168, 288);
			this.button69.Name = "button69";
			this.button69.Size = new Size(72, 32);
			this.button69.TabIndex = 80;
			this.button69.Text = "Others";
			this.button69.UseVisualStyleBackColor = false;
			this.btnOK.BackColor = Color.FromArgb(0, 64, 64);
			this.btnOK.FlatAppearance.BorderColor = Color.Green;
			this.btnOK.FlatAppearance.BorderSize = 2;
			this.btnOK.FlatStyle = FlatStyle.Flat;
			this.btnOK.Font = new Font("Arial", 12f, FontStyle.Regular, GraphicsUnit.Point, 0);
			this.btnOK.ForeColor = Color.White;
			this.btnOK.Location = new Point(408, 288);
			this.btnOK.Name = "btnOK";
			this.btnOK.Size = new Size(48, 32);
			this.btnOK.TabIndex = 83;
			this.btnOK.Text = "OK";
			this.btnOK.UseVisualStyleBackColor = false;
			this.btnOK.Click += new EventHandler(this.btnOK_Click);
			this.btnDelete.BackColor = Color.FromArgb(0, 64, 64);
			this.btnDelete.FlatAppearance.BorderColor = Color.Green;
			this.btnDelete.FlatAppearance.BorderSize = 2;
			this.btnDelete.FlatStyle = FlatStyle.Flat;
			this.btnDelete.Font = new Font("Arial", 12f, FontStyle.Regular, GraphicsUnit.Point, 0);
			this.btnDelete.ForeColor = Color.White;
			this.btnDelete.Location = new Point(312, 288);
			this.btnDelete.Name = "btnDelete";
			this.btnDelete.Size = new Size(96, 32);
			this.btnDelete.TabIndex = 82;
			this.btnDelete.Text = "DELETE";
			this.btnDelete.UseVisualStyleBackColor = false;
			this.btnDelete.Click += new EventHandler(this.btnDelete_Click);
			this.pictureBox1.BackColor = Color.MediumSeaGreen;
			this.pictureBox1.Location = new Point(0, 8);
			this.pictureBox1.Name = "pictureBox1";
			this.pictureBox1.Size = new Size(104, 72);
			this.pictureBox1.TabIndex = 84;
			this.pictureBox1.TabStop = false;
			this.lblChar1.Font = new Font("Arial", 24f, FontStyle.Underline, GraphicsUnit.Point, 0);
			this.lblChar1.ForeColor = Color.White;
			this.lblChar1.Location = new Point(144, 32);
			this.lblChar1.Name = "lblChar1";
			this.lblChar1.Size = new Size(32, 36);
			this.lblChar1.TabIndex = 85;
			this.lblChar1.Text = "_";
			this.lblChar2.Font = new Font("Arial", 24f, FontStyle.Underline, GraphicsUnit.Point, 0);
			this.lblChar2.ForeColor = Color.White;
			this.lblChar2.Location = new Point(176, 32);
			this.lblChar2.Name = "lblChar2";
			this.lblChar2.Size = new Size(32, 36);
			this.lblChar2.TabIndex = 86;
			this.lblChar2.Text = "_";
			this.lblChar3.Font = new Font("Arial", 24f, FontStyle.Underline, GraphicsUnit.Point, 0);
			this.lblChar3.ForeColor = Color.White;
			this.lblChar3.Location = new Point(208, 32);
			this.lblChar3.Name = "lblChar3";
			this.lblChar3.Size = new Size(32, 36);
			this.lblChar3.TabIndex = 87;
			this.lblChar3.Text = "_";
			this.lblChar4.Font = new Font("Arial", 24f, FontStyle.Underline, GraphicsUnit.Point, 0);
			this.lblChar4.ForeColor = Color.White;
			this.lblChar4.Location = new Point(240, 32);
			this.lblChar4.Name = "lblChar4";
			this.lblChar4.Size = new Size(32, 36);
			this.lblChar4.TabIndex = 88;
			this.lblChar4.Text = "_";
			this.lblChar5.Font = new Font("Arial", 24f, FontStyle.Underline, GraphicsUnit.Point, 0);
			this.lblChar5.ForeColor = Color.White;
			this.lblChar5.Location = new Point(272, 32);
			this.lblChar5.Name = "lblChar5";
			this.lblChar5.Size = new Size(32, 36);
			this.lblChar5.TabIndex = 89;
			this.lblChar5.Text = "_";
			this.lblChar6.Font = new Font("Arial", 24f, FontStyle.Underline, GraphicsUnit.Point, 0);
			this.lblChar6.ForeColor = Color.White;
			this.lblChar6.Location = new Point(304, 32);
			this.lblChar6.Name = "lblChar6";
			this.lblChar6.Size = new Size(32, 36);
			this.lblChar6.TabIndex = 90;
			this.lblChar6.Text = "_";
			this.lblChar7.Font = new Font("Arial", 24f, FontStyle.Underline, GraphicsUnit.Point, 0);
			this.lblChar7.ForeColor = Color.White;
			this.lblChar7.Location = new Point(336, 32);
			this.lblChar7.Name = "lblChar7";
			this.lblChar7.Size = new Size(32, 36);
			this.lblChar7.TabIndex = 91;
			this.lblChar7.Text = "_";
			base.AutoScaleMode = AutoScaleMode.None;
			this.BackColor = Color.FromArgb(0, 0, 64);
			base.ClientSize = new Size(496, 348);
			base.Controls.Add(this.lblChar7);
			base.Controls.Add(this.lblChar6);
			base.Controls.Add(this.lblChar5);
			base.Controls.Add(this.lblChar4);
			base.Controls.Add(this.lblChar3);
			base.Controls.Add(this.lblChar2);
			base.Controls.Add(this.lblChar1);
			base.Controls.Add(this.pictureBox1);
			base.Controls.Add(this.btnOK);
			base.Controls.Add(this.btnDelete);
			base.Controls.Add(this.button68);
			base.Controls.Add(this.button69);
			base.Controls.Add(this.button67);
			base.Controls.Add(this.button66);
			base.Controls.Add(this.button50);
			base.Controls.Add(this.button51);
			base.Controls.Add(this.button52);
			base.Controls.Add(this.button45);
			base.Controls.Add(this.button46);
			base.Controls.Add(this.button47);
			base.Controls.Add(this.button48);
			base.Controls.Add(this.button49);
			base.Controls.Add(this.button42);
			base.Controls.Add(this.button43);
			base.Controls.Add(this.button44);
			base.Controls.Add(this.button41);
			base.Controls.Add(this.button40);
			base.Controls.Add(this.button53);
			base.Controls.Add(this.button54);
			base.Controls.Add(this.button55);
			base.Controls.Add(this.button56);
			base.Controls.Add(this.button57);
			base.Controls.Add(this.button58);
			base.Controls.Add(this.button59);
			base.Controls.Add(this.button60);
			base.Controls.Add(this.button61);
			base.Controls.Add(this.button62);
			base.Controls.Add(this.button63);
			base.Controls.Add(this.button64);
			base.Controls.Add(this.button65);
			base.Controls.Add(this.button27);
			base.Controls.Add(this.button28);
			base.Controls.Add(this.button29);
			base.Controls.Add(this.button30);
			base.Controls.Add(this.button31);
			base.Controls.Add(this.button32);
			base.Controls.Add(this.button33);
			base.Controls.Add(this.button34);
			base.Controls.Add(this.button35);
			base.Controls.Add(this.button36);
			base.Controls.Add(this.button37);
			base.Controls.Add(this.button38);
			base.Controls.Add(this.button39);
			base.Controls.Add(this.button14);
			base.Controls.Add(this.button15);
			base.Controls.Add(this.button16);
			base.Controls.Add(this.button17);
			base.Controls.Add(this.button18);
			base.Controls.Add(this.button19);
			base.Controls.Add(this.button20);
			base.Controls.Add(this.button21);
			base.Controls.Add(this.button22);
			base.Controls.Add(this.button23);
			base.Controls.Add(this.button24);
			base.Controls.Add(this.button25);
			base.Controls.Add(this.button26);
			base.Controls.Add(this.button13);
			base.Controls.Add(this.button12);
			base.Controls.Add(this.button11);
			base.Controls.Add(this.button10);
			base.Controls.Add(this.button9);
			base.Controls.Add(this.button8);
			base.Controls.Add(this.button7);
			base.Controls.Add(this.button6);
			base.Controls.Add(this.button5);
			base.Controls.Add(this.button4);
			base.Controls.Add(this.button3);
			base.Controls.Add(this.button2);
			base.Controls.Add(this.button1);
			base.Name = "NameEntry";
			this.Text = "NameEntry";
			((ISupportInitialize)this.pictureBox1).EndInit();
			base.ResumeLayout(false);
		}
		public NameEntry(Bitmap b)
		{
			this.InitializeComponent();
			this.chars = new Label[]
			{
				this.lblChar1,
				this.lblChar2,
				this.lblChar3,
				this.lblChar4,
				this.lblChar5,
				this.lblChar6,
				this.lblChar7
			};
			this.pictureBox1.Image = b;
		}
		public string enterName()
		{
			base.ShowDialog();
			return this.name;
		}
		private void btnLetter_Click(object sender, EventArgs e)
		{
			if (this.name.Length < 7)
			{
				string text = ((Button)sender).Text;
				this.name += text;
				this.chars[this.pos++].Text = text;
			}
		}
		private void btnOK_Click(object sender, EventArgs e)
		{
			base.Close();
		}
		private void btnDelete_Click(object sender, EventArgs e)
		{
			this.name = this.name.Remove(--this.pos, 1);
			this.chars[this.pos].Text = "_";
		}
	}
}
